### ISSUE TITLE
No map loaded with refined_coot.py if not using half-maps

### ISSUE THREAD

**Issue by daniel-s-d-larsson** [keitaroyam/servalcat#18]
When I refine a structure with a full map, the refined_coot.py script does not load the map itself in Coot, just the difference map. The size of the refined_diffmap.mtz seems smaller than the diffmap.mtz produce from running with half-maps, so perhaps the mtz file is not complete? Perhaps the coot script could be modified to load the input map for the refinement instead?

**Comment by keitaroyam** [comment]
While it's possible to use a single map, we generally recommend using half maps for optimal results. The difference map can also be less effective due to the inherent challenges in calculating weights and sharpening values. Therefore, I am hesitant to add more support for the single-map mode at this time.

**Comment by Guillawme** [comment]
Given that it is mandatory to deposit half-maps, I think it would be ok to completely remove the single-map mode. With sufficient advance notice, and a deprecation period over several CCP4 updates, that should be fine.

**Comment by keitaroyam** [comment]
I think it's fair. However, single-map mode is still useful for some older EMDB maps, and there has been requests for this feature. I hope to eventually remove this mode.

**Comment by Guillawme** [comment]
Ah, then I agree it's good to have when looking at EMDB entries that pre-date the mandatory deposition of half-maps. It is fine to keep, if the documentation and help message say prominently that it should only be used for these cases.
