### ISSUE TITLE
numpy>=1.19.1 required for pandas>=1.3.0

### ISSUE THREAD

**Issue by keitaroyam** [keitaroyam/servalcat#2]
Because the following code fails with numpy<1.19.1, it is incompatible with pandas 1.3.0, which introduced https://github.com/pandas-dev/pandas/blob/f00ed8f47020034e752baf0250483053340971b0/pandas/core/internals/concat.py#L533. 
```py
numpy.dtype(numpy.complex128).type("NaN") 
```

**Comment by simonmiljan** [comment]
I encountered a new problem when running servalcat on one of my machines (see attached log). Could you please advise what could be the source of the problem?
[servalcat-error.log](https://github.com/keitaroyam/servalcat/files/7611861/servalcat-error.log)

**Comment by keitaroyam** [comment]
> ERROR: CLIBD_MON is not set

Did you source the CCP4 setup script?

**Comment by simonmiljan** [comment]
Hm, not really. See an example of my script file. I've encountered this error on one of the three machines.
[servalcat.txt](https://github.com/keitaroyam/servalcat/files/7611907/servalcat.txt)

**Comment by simonmiljan** [comment]
When run under tcsh (this is MacOS machine; High Sierra), the program ran a bit longer but crashed again; see the new log file.
[servalcat.log](https://github.com/keitaroyam/servalcat/files/7611912/servalcat.log)

**Comment by keitaroyam** [comment]
> AttributeError: 'gemmi.Topo' object has no attribute 'chain_infos'

This is related to the very latest gemmi from github. Sorry for the inconvenience. Please uninstall gemmi and install the package version:
```
pip uninstall gemmi
pip install gemmi
```

**Comment by simonmiljan** [comment]
When I use those commands, gemmi 0.5.0 is installed again. How do I install the earlier version of gemmi?

**Comment by keitaroyam** [comment]
gemmi 0.5.0 should work. If you need earlier version by some reason, you can try `pip install gemmi==0.4.9`.

**Comment by simonmiljan** [comment]
It's working now with either gemmi version. Thank you!

**Comment by keitaroyam** [comment]
Good, thanks. If you have any further questions, please open a new issue (as this thread is about numpy and pandas problem).

**Comment by simonmiljan** [comment]
Thank you!
