### ISSUE TITLE
Restraining secondary structures

### ISSUE THREAD

**Issue by helgepat** [keitaroyam/servalcat#7]
Hi again,

I am currently refining a model against a low-resolution map which contains some areas with bad density. Generally, the servalcat output looks good, just some of the secondary structure in the bad density-regions gets destroyed.
Therefore, I was wondering how I could restrain the secondary structures during the run. I assume that I have to run ProSmart (with some specific settings for secondary structure?) and apply this to a refmac keyword? Could you maybe let me know if this is possible with servalcat and how to achieve it?

Thanks for reading,

Helge

**Comment by keitaroyam** [comment]
Thanks for your message. Yes, I can imagine it would happen at lower resolution, where reference structure or secondary structure restraint definitely help. You may also want to use `--keywords "vdwr 2"` to reduce clashes.

For secondary structure restraints, yes, you can use ProSmart with `-h` option. For example,
```sh
prosmart -p1 your_model.pdb -h -o prosmart_h
```
then you will have prosmart_h/your_model.txt (file name is determined based on your input file name). Then run refinement like
```sh
servalcat refine_spa --keyword_file prosmart_h/your_model.txt [other options...]
```

Before this, you can visually check these restraints using Coot:
1. open your model
2. Calculate - Modules - Restraints
3. give your path to prosmart text file in Restraints - Read Refmac Extra Restraints
4. you will see coloured lines between restrained atom pairs.

**Comment by helgepat** [comment]
Thank you for the input, I have tried refinement with the prosmart restraints and it does not help in my case. I realized that my secondary structure was not perfect in the regions in question even before refinement, its just that ChimeraX was still showing annotated beta-strands... I think ChimeraX is quite tolerant to imperfect secondary structure? Anyway, I still have to manually fix the model before refinement and see if the structure stays intact. I tried using Coot with dedicated beta-strand restraints, but this did not seem to do anything to the residues, so I have to investigate this in more detail... (alpha-helical restraints nicely enfore the correct geometry).

**Comment by keitaroyam** [comment]
I am not familiar with ChimeraX, but it may be using metadata in the coordinate file. If you are using a model from PDB or phenix (with secondary structure restraints), the file should contain such header. Beta-strand restraints in Coot (in my understanding) just set up pseudo bond and angle restraints between i th and i+1 (or i+2) th residues, and do not try to make hydrogen bonds for sheets.

If you have some good external structures (high resolution homolog or AF2 predicted model), I would use them to rebuild that part of the model (e.g. in Coot using self-restraints and all-atom refinement) or use prosmart (not -h) to prepare restraints and use them in servalcat/refmac. I would prefer starting with the first option if heavily distorted (and then second option to keep conformation during the refinement).
